name: a2a_helloworld_env
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.4=haa95532_0
  - click=8.0.3=pyhd3eb1b0_0
  - expat=2.7.3=h9214b88_0
  - h11=0.16.0=py314haa95532_1
  - idna=3.11=py314haa95532_0
  - libffi=3.4.4=hd77b12b_1
  - libmpdec=4.0.0=h827c3e9_0
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - openssl=3.0.18=h543e019_0
  - pip=25.3=pyh0d26453_0
  - python=3.14.0=h3bc0a5a_101_cp314
  - python_abi=3.14=2_cp314
  - sqlite=3.51.0=hda9a48d_0
  - starlette=0.47.3=py314haa95532_0
  - tk=8.6.15=hf199647_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - uvicorn=0.35.0=py314haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - a2a-sdk==0.3.19
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.11.0
      - cachetools==6.2.2
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - fastapi==0.122.0
      - google-api-core==2.28.1
      - google-auth==2.43.0
      - googleapis-common-protos==1.72.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - httpx-sse==0.4.3
      - proto-plus==1.26.1
      - protobuf==6.33.1
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - requests==2.32.5
      - rsa==4.9.1
      - sniffio==1.3.1
      - sse-starlette==3.0.3
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - urllib3==2.5.0
